# Change these first
owner: weblate-status-bot
repo: nijel-status
user-agent: weblate-status-bot

# Add your sites here
sites:
  - name: cihar.com
    url: https://cihar.com/
  - name: blog.cihar.com
    url: https://blog.cihar.com/
  - name: wammu.eu
    url: https://wammu.eu/
  - name: bypetula.cz
    url: https://bypetula.cz/
  - name: darky.cihar.com
    url: https://darky.cihar.com/
  - name: svatba.cihar.com
    url: https://svatba.cihar.com/
  - name: webmail.cihar.com
    url: https://webmail.cihar.com/
  - name: apartmancvikov.cz
    url: https://apartmancvikov.cz/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.cihar.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Status monitoring for my websites.
  introMessage: This is a status page for sites I maintain and are not covered by other monitoring.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
